### ISSUE TITLE
Missing UN/LOCODEs for cities and towns

### ISSUE THREAD

**Issue by lgloege** [Open-Earth-Foundation/OpenClimate-UNLOCODE#1]
Many LOCODEs are missing from this dataset. 

For example, I do not see Aljaraque in Spain, which is LOCODE ES-ZAI

One solution would be to scrape LOCODEs from the web. UNECE has LOCODEs stored in HTML tables (https://service.unece.org/trade/locode/es.htm), looks fairly easy to scrape. Change the  ISO 3166-1  code in the URL to scrape a different country. @evanp

**Comment by lgloege** [comment]
Can also download from here: https://unece.org/trade/uncefact/unlocode

**Comment by evanp** [comment]
@lgloege this data is originally from the LOCODE web site. The problem I initially ran into was that UNLOCODE does not distinguish between cities and other commercially important locations like airports and seaports.

I tried to filter out stuff that wasn't cities by using the "function" code. I only used entries that had function 3, "road terminal". That seems to have worked in certain situations, but not in others, and we've got some false negatives.

Do you want to do a list of cities and towns that you think are missing, and we can see if there's an easy pattern to include them?

**Comment by lgloege** [comment]
Instead of using the function codes I filtered the name  using a regular expression. It's not the most compact or efficient  expression, but it gets the job done.  This change and the updated csv files are in the `filter` branch.

```python
    regex = (
        '^Port\sof'
        '|\sPort$'
        '|\sPt\s?/'
        '|Pt\.'
        '|\sPort\s?/'
        '|\sApt\s?/'
        '|\sApt$'
        '|\sRailway\sStation.*'
        '|\sFerryport'
        '|Ferry\sPort'
        '|\sTerminal'
        '|.+Airport'
    )

    if re.search(regex, row["Name"]):
        return
```
